POST http://localhost:3000/api/doctores/
Content-Type: application/json

{
  "id_doctor": 2,
  "nombre": "Pedro",
  "apellido": "Pérez",
  "numero_tel": 55351234,
  "direccion": "Calle Falsa 1223"
}

###

GET http://localhost:3000/api/doctores

###

GET http://localhost:3000/api/doctores/1