POST http://localhost:3000/api/doctores/
Content-Type: application/json

{
  "id_doctor": 3,
  "nombre": "Pedro_2",
  "apellido": "Pérez",
  "numero_tel": 55351234,
  "direccion": "Calle Falsa 122334"
}

###

GET http://localhost:3000/api/doctores

###

GET http://localhost:3000/api/doctores/1